FROM python:3-alpine3.8

EXPOSE 8001
WORKDIR /tmp
COPY requirements.txt /tmp
WORKDIR /tmp
RUN pip3 install -r requirements.txt
COPY main.py /home/src
CMD ["python", "./main.py" ]
ENTRYPOINT ["/bin/echo", "Installation successfully!!"]

